# Generated by Django 5.1.5 on 2025-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('email_id', models.CharField(max_length=25, unique=True)),
                ('course_id', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
