# Generated by Django 5.1.5 on 2025-02-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.CharField(max_length=25),
        ),
    ]
