# Generated by Django 5.1.5 on 2025-03-01 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_contact_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: start with 7, 8, 9 and remaining 9 digit is 0 to 9', regex='^[789]\\d{9}$')]),
        ),
    ]
