# Generated by Django 5.1.5 on 2025-01-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=5)),
                ('student_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('mob_no', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=250)),
                ('admission_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('course_id', models.CharField(max_length=25)),
                ('session', models.CharField(max_length=10)),
                ('fee', models.CharField(max_length=10)),
            ],
        ),
    ]
