# Generated by Django 5.1.5 on 2025-02-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=5)),
                ('payment_date', models.DateField()),
            ],
        ),
    ]
