# Generated by Django 5.1.5 on 2025-02-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_remove_student_id_alter_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=10),
        ),
    ]
