# Generated by Django 5.1.5 on 2025-02-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0019_alter_fee_roll_no_alter_result_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
