# Generated by Django 5.1.5 on 2025-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0021_alter_result_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='fee',
            name='roll_no',
            field=models.IntegerField(verbose_name=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='mob_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
