# Generated by Django 5.1.5 on 2025-02-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0023_alter_student_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
