# Generated by Django 5.1.5 on 2025-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0027_alter_course_course_name_alter_student_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.CharField(max_length=25),
        ),
    ]
