# Generated by Django 5.1.5 on 2025-02-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0028_alter_course_course_name_alter_student_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminPanel.course'),
        ),
    ]
