# Generated by Django 5.1.5 on 2025-02-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0032_alter_student_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.CharField(max_length=25),
        ),
    ]
