# Generated by Django 5.1.5 on 2025-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0035_alter_fee_roll_no_alter_result_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='No description yet', max_length=200),
        ),
    ]
