# Generated by Django 5.1.5 on 2025-04-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0036_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='roll_no',
            field=models.CharField(max_length=10),
        ),
    ]
