# Generated by Django 5.1.5 on 2025-04-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0040_alter_fee_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
