# Generated by Django 5.1.5 on 2025-04-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0041_alter_fee_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='roll_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
