# Generated by Django 5.1.5 on 2025-04-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0042_alter_fee_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='roll_no',
        ),
    ]
