# Generated by Django 5.1.5 on 2025-04-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0043_remove_fee_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='roll_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
