# Generated by Django 5.1.5 on 2025-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0045_alter_fee_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='roll_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='roll_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=10),
        ),
    ]
